---
kind: pipeline
name: k3s-root-linux-amd64
platform:
  os: linux
  arch: amd64

workspace:
  path: /workdir
    
steps:
  - name: build-amd64
    image: rancher/dapper:v0.5.0
    environment:
      BUILDARCH: amd64
    commands:
    - dapper ci
    volumes:
    - name: docker
      path: /var/run/docker.sock
  - name: stage-amd64-binaries
    image: ubuntu:18.04
    commands:
    - "mkdir -p /workdir/dist"
    - "tar cf - -C /workdir ./bin ./etc > /workdir/dist/k3s-root-amd64.tar"
    - "tar cf - -C /workdir --transform s/xtables-bin/bin/ ./xtables-bin > /workdir/dist/k3s-root-xtables-amd64.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: github-amd64-binary-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
      - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      prerelease: true
      files:
      - "/workdir/dist/k3s-*.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: k3s-root-linux-arm64
platform:
  os: linux
  arch: amd64

workspace:
  path: /workdir
    
steps:
  - name: build-arm64
    image: rancher/dapper:v0.5.0
    environment:
      BUILDARCH: arm64
    commands:
    - dapper ci
    volumes:
    - name: docker
      path: /var/run/docker.sock
  - name: stage-arm64-binaries
    image: ubuntu:18.04
    commands:
    - "mkdir -p /workdir/dist"
    - "tar cf - -C /workdir ./bin ./etc > /workdir/dist/k3s-root-arm64.tar"
    - "tar cf - -C /workdir --transform s/xtables-bin/bin/ ./xtables-bin > /workdir/dist/k3s-root-xtables-arm64.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: github-arm64-binary-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
      - sha256
      checksum_file: CHECKSUMsum-arm64.txt
      checksum_flatten: true
      prerelease: true
      files:
      - "/workdir/dist/k3s-*.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: k3s-root-linux-arm
platform:
  os: linux
  arch: amd64

workspace:
  path: /workdir
    
steps:
  - name: build-arm
    image: rancher/dapper:v0.5.0
    environment:
      BUILDARCH: arm
    commands:
    - dapper ci
    volumes:
    - name: docker
      path: /var/run/docker.sock
  - name: stage-arm-binaries
    image: ubuntu:18.04
    commands:
    - "mkdir -p /workdir/dist"
    - "tar cf - -C /workdir ./bin ./etc > /workdir/dist/k3s-root-arm.tar"
    - "tar cf - -C /workdir --transform s/xtables-bin/bin/ ./xtables-bin > /workdir/dist/k3s-root-xtables-arm.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: github-arm-binary-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
      - sha256
      checksum_file: CHECKSUMsum-arm.txt
      checksum_flatten: true
      prerelease: true
      files:
      - "/workdir/dist/k3s-*.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: k3s-root-linux-ppc64le
platform:
  os: linux
  arch: amd64

workspace:
  path: /workdir
    
steps:
  - name: build-ppc64le
    image: rancher/dapper:v0.5.0
    environment:
      BUILDARCH: ppc64le
    commands:
    - dapper ci
    volumes:
    - name: docker
      path: /var/run/docker.sock
  - name: stage-ppc64le-binaries
    image: ubuntu:18.04
    commands:
    - "mkdir -p /workdir/dist"
    - "tar cf - -C /workdir ./bin ./etc > /workdir/dist/k3s-root-ppc64le.tar"
    - "tar cf - -C /workdir --transform s/xtables-bin/bin/ ./xtables-bin > /workdir/dist/k3s-root-xtables-ppc64le.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
  - name: github-ppc64le-binary-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
      - sha256
      checksum_file: CHECKSUMsum-ppc64le.txt
      checksum_flatten: true
      prerelease: true
      files:
      - "/workdir/dist/k3s-*.tar"
    when:
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock